steps:
  - name: gcr.io/cloud-builders/docker
    args:
    - 'build'
    - '-f'
    - './cmd/auth/Dockerfile'
    - '-t'
    - 'gcr.io/$PROJECT_ID/skygear-auth:git-$SHORT_SHA'
    - '-t'
    - 'gcr.io/$PROJECT_ID/skygear-auth:next'
    - '.'
    id: 'skygear-auth'
  - name: gcr.io/cloud-builders/docker
    args:
    - 'build'
    - '-f'
    - './cmd/gateway/Dockerfile'
    - '-t'
    - 'gcr.io/$PROJECT_ID/skygear-gateway:git-$SHORT_SHA'
    - '-t'
    - 'gcr.io/$PROJECT_ID/skygear-gateway:next'
    - '.'
    id: 'skygear-gateway'
  - name: gcr.io/cloud-builders/docker
    args:
    - 'build'
    - '-f'
    - './cmd/record/Dockerfile'
    - '-t'
    - 'gcr.io/$PROJECT_ID/skygear-record:git-$SHORT_SHA'
    - '-t'
    - 'gcr.io/$PROJECT_ID/skygear-record:next'
    - '.'
    id: 'skygear-record'
images:
- 'gcr.io/$PROJECT_ID/skygear-auth:git-$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/skygear-auth:next'
- 'gcr.io/$PROJECT_ID/skygear-gateway:git-$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/skygear-gateway:next'
- 'gcr.io/$PROJECT_ID/skygear-record:git-$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/skygear-record:next'
